FROM node:22-alpine3.20

WORKDIR /app

# Create non-root user
RUN addgroup -g 1001 -S nodejs
RUN adduser -S nodeuser -u 1001

COPY package*.json ./
RUN npm ci --only=production && npm cache clean --force

COPY --chown=nodeuser:nodejs . .

USER nodeuser

EXPOSE 5000
CMD ["node", "server.js"]